export const COMIC_FACTS = [
  "Superman's first appearance in Action Comics #1 (1938) sold for $3.2 million in 2014.",
  "Wolverine was originally intended to be an actual wolverine mutated into human form.",
  "Before becoming Iron Man, Tony Stark's original armor was gray, not red and gold.",
  "Spider-Man was rejected by Marvel at first because Stan Lee's publisher thought readers hated spiders.",
  "The first comic book ever published was 'Famous Funnies' in 1933.",
  "Batman was originally going to be called 'Bird-Man' before Bob Kane changed his mind.",
  "Deadpool's real name, Wade Wilson, is a parody of DC's Deathstroke (Slade Wilson).",
  "The X-Men were originally called 'The Merry Mutants' during early development.",
  "Captain America's shield is made of vibranium, the same metal as Black Panther's suit.",
  "Venom was originally designed as a female character before becoming Eddie Brock.",
  "The Joker was almost cut after his first appearance because he was considered too evil.",
  "Wonder Woman was created by the same psychologist who invented the lie detector test.",
  "Hawkeye and Green Arrow debuted the same year (1941) for rival publishers.",
  "The first Black superhero in mainstream comics was Black Panther in 1966.",
  "Ghost Rider was originally going to be called 'Ghost Racer' and ride a horse.",
  "Stan Lee made cameos in Marvel films as a tribute to his co-creation of many characters.",
  "The Hulk was originally gray, but printing issues led Marvel to change him to green.",
  "Wolverine's claws were originally supposed to be part of his gloves, not his body.",
  "Thor's hammer Mjolnir is inscribed: 'Whosoever holds this hammer, if he be worthy...'",
  "The Flash can run faster than the speed of light and has even outrun death itself.",
  "Aquaman can control all sea life because he's telepathic, not because he 'talks to fish.'",
  "The Fantastic Four were Marvel's first superhero team, debuting in 1961.",
  "Robin's original costume was inspired by the legendary Robin Hood.",
  "Magneto and Professor X were inspired by Malcolm X and Martin Luther King Jr.",
  "The rarest comic is Action Comics #1, with fewer than 100 copies known to exist.",
  "Spawn's cape is actually alive and can respond to his thoughts.",
  "Harley Quinn was created for Batman: The Animated Series, not the comics.",
  "The Punisher's skull logo has been worn by military and police units worldwide.",
  "Teenage Mutant Ninja Turtles started as a parody of popular comics like Daredevil.",
  "Thanos was inspired by the DC villain Darkseid and the Freudian concept of Thanatos.",
  "Nick Fury was originally white in the comics; the Samuel L. Jackson version was from the Ultimate universe.",
  "The Comics Code Authority banned vampires, werewolves, and zombies from comics for nearly 20 years.",
  "Blade first appeared as a supporting character in Tomb of Dracula #10 (1973).",
  "Ms. Marvel (Kamala Khan) was the first Muslim character to headline a Marvel comic.",
  "Superman once arm-wrestled Muhammad Ali in a 1978 DC comic special.",
  "The term 'graphic novel' was popularized by Will Eisner's 'A Contract with God' in 1978.",
  "Squirrel Girl has canonically defeated Thanos, Doctor Doom, and Galactus.",
  "The first comic book to sell for over $1 million was a CGC 8.0 copy of Action Comics #1 in 2010.",
  "Kitty Pryde of the X-Men was only 13 years old when she first joined the team.",
  "Iron Man's Extremis armor was the first to be stored inside Tony Stark's body.",
  "The Infinity Gauntlet storyline killed half of all life in the universe, including most Avengers.",
  "Ant-Man can shrink to the subatomic level and enter the Quantum Realm.",
  "DC's Lobo was created as a parody of violent comic book antiheroes like Wolverine.",
  "The original Human Torch was an android, not Johnny Storm of the Fantastic Four.",
  "Rocket Raccoon first appeared in Marvel Preview #7 (1976), years before Guardians of the Galaxy.",
  "Jean Grey has died and been resurrected more times than any other X-Men character.",
  "The Sandman by Neil Gaiman won a World Fantasy Award, the first comic to do so.",
  "Batman has a contingency plan to defeat every member of the Justice League.",
  "Daredevil's radar sense lets him 'see' better than most sighted people.",
  "The original Captain Marvel (Shazam) once outsold Superman in the 1940s.",
  "Cable is the son of Cyclops and a clone of Jean Grey named Madelyne Pryor.",
  "Howard the Duck ran for President of the United States in his 1976 comic series.",
  "The Green Lantern oath was written by Alfred Bester, a famous science fiction author.",
  "Galactus was originally drawn as a god-like figure, not a man in purple armor.",
  "Miles Morales was co-created by Brian Michael Bendis and artist Sara Pichelli in 2011.",
  "The Death of Superman in 1992 sold over 6 million copies.",
  "Watchmen was originally going to use characters DC acquired from Charlton Comics.",
  "John Constantine (Hellblazer) was designed to look like the musician Sting.",
  "Captain America was punching Hitler on the cover of his first comic in March 1941, before the US entered WWII.",
  "The Batcave was invented for the 1943 Batman movie serial, then added to comics.",
  "X-23 (Laura Kinney) was created for the X-Men: Evolution animated series before appearing in comics.",
  "Poison Ivy was originally a one-off Batman villain in 1966 before becoming iconic.",
  "The Superman 'S' symbol means 'hope' on Krypton.",
  "Moon Knight has multiple personalities: Marc Spector, Steven Grant, and Jake Lockley.",
  "Red Skull's face is not a mask. It's his actual face after a botched super-soldier serum.",
  "Gwenpool started as a joke variant cover before getting her own comic series.",
  "The Teen Titans were originally called the 'Junior Justice League' in early concepts.",
  "Doctor Strange was a greedy surgeon before a car accident led him to the mystic arts.",
  "Groot's vocabulary is limited because his species' vocal cords harden as they age.",
  "Black Widow was originally introduced as an Iron Man villain in 1964.",
  "Nightcrawler's father is the demon Azazel, making him part-demon.",
  "The Joker's real name and origin have never been definitively confirmed in comics.",
  "Martian Manhunter is considered one of the most powerful Justice League members.",
  "Emma Frost started as a villain (the White Queen) before joining the X-Men.",
  "The Batman Who Laughs is a version of Batman infected with Joker toxin.",
  "Rogue permanently absorbed Ms. Marvel's powers after holding on too long.",
  "Storm was worshipped as a goddess in Kenya before joining the X-Men.",
  "Frank Miller's The Dark Knight Returns (1986) redefined Batman as a darker character.",
  "The Savage Dragon by Erik Larsen has been continuously written and drawn by him since 1992.",
  "Kryptonite was invented for the Superman radio show so the voice actor could take vacations.",
  "Jessica Jones was originally going to be named Jessica Drew (Spider-Woman's name).",
];

export function getRandomFact(): string {
  return COMIC_FACTS[Math.floor(Math.random() * COMIC_FACTS.length)];
}
